### ISSUE TITLE
CRC32_USE_LOOKUP_TABLE_SLICING_BY_4 not defined in Crc32.h

### ISSUE THREAD

**Issue by tansy** [stbrumme/crc32#1]
In Crc32.h there is 
`CRC32_USE_LOOKUP_TABLE_SLICING_BY_8` is defined twice and `CRC32_USE_LOOKUP_TABLE_SLICING_BY_4` is not defined at all. Changing it allows to actually have slicing-by-4 algorithm in test.
 
Crc32.h.diff:
```
12c12
< #define CRC32_USE_LOOKUP_TABLE_SLICING_BY_8
---
> #define CRC32_USE_LOOKUP_TABLE_SLICING_BY_4
```

**Comment by stbrumme** [comment]
thanks for spotting that copy-pasta error. It's fixed in version 8.
