### ISSUE TITLE
Makefile doesn't trigger -O3

### ISSUE THREAD

**Issue by deisenstein** [stbrumme/crc32#3]
We want to pass along that the Makefile doesn't currently use the FLAGS, so that the out-of-the-box compiling doesn't invoke -O3 (or any optimization).  Turning that on sped up the 16-way code by a factor of 4 and got us up to the speed on your web page.

Thanks for making this code available!  It works nicely and was easy to read.

**Comment by stbrumme** [comment]
Thanks for pointing that out.
A new Makefile was checked in.
