### ISSUE TITLE
Mac OS byte order 

### ISSUE THREAD

**Issue by ArtemKotovsky** [stbrumme/crc32#7]
[macOsByteOrder.patch.txt](https://github.com/stbrumme/crc32/files/3907007/macOsByteOrder.patch.txt)

The __BYTE_ORDER and __BIG_ENDIAN macros are not defined at MAC OS
    X CODE Version 11.2.1 (11B500)
    all hash functions except of 1byte-version uses big_endian by default - it is a reason of wrong hashes

**Comment by stbrumme** [comment]
see discussion https://github.com/stbrumme/crc32/pull/8
